server:
  port: 8182

kafka-config:
  boot-strap-server: localhost:19092, localhost:29092, localhost:39092
  schema-registry-uri-key: schema.registry.url
  schema-registry-uri: http://localhost:8081
  topic-name: twitter-topic
  topics:
    - twitter-topic

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  consumer-group-id: twitter-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: false
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

retry-config:
  initial-interval-mi: 1000
  max-interval-mi: 10000
  multiplier: 2.0
  max-retry: 3
  sleep-time-mi: 2000

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  is-repository: true
